UMC-CodePlay/CodePlay-BE

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/etc-issue-template.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
> 이슈: 제목 및 레이블, 의무 진행사항 추가
> pr: 의무 진행사항 추가
=> [Docs] issue, pr template 수정

.github/workflows/build-test.yml, build.gradle, src/main/java/umc/codeplay/CodeplayApplication.java, src/test/java/umc/codeplay/CodeplayApplicationTests.java
- closes #15 
> spotless 설정 변경
=> #15 ci test

build.gradle, src/main/java/umc/codeplay/controller/MemberViewController.java, src/main/java/umc/codeplay/converter/MemberConverter.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/dto/MemberRequestDTO.java, src/main/java/umc/codeplay/dto/MemberResponseDTO.java, src/main/java/umc/codeplay/repository/MemberRepository.java, src/main/java/umc/codeplay/service/MemberService.java
- closes #12 
기본 로그인 세팅.
로그인 세부 세팅 필요합니다.
=> 기본 회원가입 설정(#12)

src/main/java/umc/codeplay/controller/HealthCheck.java
- closes #54 
> health check시 http status를 반환하도록 변경
> 테스트 통과
=> [Fix] Health check시 responseEntity 사용

src/main/java/umc/codeplay/config/WebConfig.java
- closes #43 
> 프론트 연동을 위한 cors 설정 추가, 모든 출처와 경로로 요청 허용
> 클라이언트에서의 테스트 필요
=> [Feat] client 요청시 cors 전체 허용으로 설정

.github/workflows/build-test.yml
=> [Fix] Update build-test.yml

.github/workflows/build-test.yml
This reverts commit 8e27c98641b9e6ab665b061454ddbc15108b872c.
- closes #
=> Revert "[Fix] Update build-test.yml (#64)"

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/controller/LikeController.java, src/main/java/umc/codeplay/converter/MusicLikeConverter.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/dto/LikeRequestDTO.java, src/main/java/umc/codeplay/dto/LikeResponseDTO.java, src/main/java/umc/codeplay/repository/MusicLikeRepository.java, src/main/java/umc/codeplay/repository/MusicRepository.java, src/main/java/umc/codeplay/service/LikeService.java
=> [Feat] 즐겨찾기 추가/삭제 (#36)

.github/workflows/build-test.yml
=> [Refactor] 환경변수 추가에 따른 Update build-test.yml

src/main/resources/application-prod.yml
=> [Fix] 배포 환경에 환경변수 추가

.github/workflows/build-test.yml
=> [Test] Update build-test.yml

src/main/java/umc/codeplay/controller/HealthCheck.java, src/main/java/umc/codeplay/dto/LikeRequestDTO.java, src/main/java/umc/codeplay/dto/LikeResponseDTO.java, src/main/java/umc/codeplay/dto/MemberRequestDTO.java
=> [Style] 간격 및 필요없는 코드 제거

src/main/java/umc/codeplay/CodeplayApplication.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/domain/common/BaseEntity.java
=> [Fix] baseEntity 자동 반영되도록 수정

src/main/java/umc/codeplay/config/AWSConfig.java
=> [Test] 필요없는 부분 제거 테스트

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/config/SwaggerConfig.java, src/main/java/umc/codeplay/controller/FileController.java, src/main/java/umc/codeplay/service/FileService.java
=> [Refactor] 파일 다운로드 로직 업데이트

src/main/java/umc/codeplay/config/security/CustomUserDetails.java, src/main/java/umc/codeplay/config/security/CustomUserDetailsService.java, src/main/java/umc/codeplay/controller/MemberController.java, src/main/java/umc/codeplay/converter/MemberConverter.java, src/main/java/umc/codeplay/domain/enums/Role.java, src/main/java/umc/codeplay/dto/MemberRequestDTO.java, src/main/java/umc/codeplay/dto/MemberResponseDTO.java, src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java, src/main/java/umc/codeplay/service/MemberService.java, src/main/resources/application.yml
- closes #32 
> 사용자의 프로필 이미지, 비밀번호 변경
=> [Feat]UpdateMemberInfo(#32)

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/converter/MusicLikeConverter.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/dto/LikeResponseDTO.java, src/main/java/umc/codeplay/repository/MusicLikeRepository.java, src/main/java/umc/codeplay/service/LikeService.java
- closes #97 
> ex) 좋아요 추가 에러 수정 , 중복 좋아요 방지.
=> [Fix]좋아요추가수정#97

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/converter/MusicLikeConverter.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/dto/LikeResponseDTO.java, src/main/java/umc/codeplay/repository/MusicLikeRepository.java, src/main/java/umc/codeplay/service/LikeService.java
Co-authored-by: 이찬우
- closes #
=> 3.5차 배포 [Fix] 좋아요추가수정 (#98)

src/main/java/umc/codeplay/controller/OAuthController.java
=> [chore] swagger hidden

src/main/java/umc/codeplay/controller/OAuthController.java
=> 2.6차 배포 [chore] swagger hidden (#100)

src/main/java/umc/codeplay/controller/FileController.java, src/main/java/umc/codeplay/domain/enums/FileType.java, src/main/java/umc/codeplay/dto/FileResponseDTO.java, src/main/java/umc/codeplay/service/FileService.java
=> [Refactor] fileUpload시 image일 경우 분기

src/main/java/umc/codeplay/controller/FileController.java, src/main/java/umc/codeplay/domain/enums/FileType.java, src/main/java/umc/codeplay/dto/FileResponseDTO.java, src/main/java/umc/codeplay/service/FileService.java
=> 배포 2.7차 [Refactor] fileUpload시 image일 경우 분기 (#102)

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/controller/FileController.java, src/main/java/umc/codeplay/controller/ModelResultController.java, src/main/java/umc/codeplay/converter/MemberConverter.java, src/main/java/umc/codeplay/domain/Harmony.java, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/domain/Remix.java, src/main/java/umc/codeplay/domain/Task.java, src/main/java/umc/codeplay/domain/Track.java, src/main/java/umc/codeplay/domain/enums/JobType.java, src/main/java/umc/codeplay/domain/enums/ProcessStatus.java, src/main/java/umc/codeplay/dto/MemberResponseDTO.java, src/main/java/umc/codeplay/dto/ModelRequestDTO.java, src/main/java/umc/codeplay/dto/ModelResponseDTO.java, src/main/java/umc/codeplay/repository/HarmonyRepository.java, src/main/java/umc/codeplay/repository/RemixRepository.java, src/main/java/umc/codeplay/repository/TaskRepository.java, src/main/java/umc/codeplay/repository/TrackRepository.java, src/main/java/umc/codeplay/service/ModelService.java
- closes #119, #120, #121 
> 기능별 결과 저장하는 post api 생성
=> [Feat] 파이썬 로컬 서버 결과 db에 반영

docker/local/deleteEvent.sql, src/main/java/umc/codeplay/domain/Member.java, src/main/java/umc/codeplay/domain/Music.java, src/main/java/umc/codeplay/domain/Remix.java, src/main/java/umc/codeplay/repository/RemixRepository.java
=> [Feat] 특정 기간 후 입력/결과 데이터 자동 삭제

src/main/java/umc/codeplay/domain/Task.java, src/main/java/umc/codeplay/domain/enums/JobType.java
=> [Fix] 잘못된 enum명 수정

src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java, src/main/java/umc/codeplay/controller/AuthController.java, src/main/java/umc/codeplay/controller/LikeController.java, src/main/java/umc/codeplay/dto/MemberRequestDTO.java, src/main/java/umc/codeplay/service/EmailService.java, src/main/java/umc/codeplay/service/MemberService.java
- closes #114 
> ex) 비밀번호 찾기를 통한 비밀번호 재설정 추가.
=> [Feat]비밀번호 재설정 #114

src/main/java/umc/codeplay/dto/MemberRequestDTO.java
=> 에러처리 내용 변경

src/main/java/umc/codeplay/config/WebConfig.java
=> cors 헤더 추가 (#144)

src/main/java/umc/codeplay/config/SecurityConfig.java
* cors 헤더 추가
* cors 에러 해결
- closes #
=> Chain (#146)

src/main/java/umc/codeplay/controller/TaskController.java, src/main/java/umc/codeplay/converter/TaskConverter.java, src/main/java/umc/codeplay/dto/TaskResponseDTO.java, src/main/java/umc/codeplay/service/TaskService.java
- closes #153 
>taskId로 harmony, track, remix를 조회할 수 있습니다.
>
=> Feat/search with task id/#153

src/main/resources/application-prod.yml, src/main/resources/application.yml
=> fix application-prod
